### ISSUE TITLE
Lovelace card overhanging

### ISSUE THREAD

**Issue by Andrewpaps** [totaldebug/atomic-calendar-revive#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Card is overlapping with others in view.

### Expected behaviour

Card should be flush with those next to it.

### Card Version

6.1.2

### Home Assistant Version

2021.11.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andrewpaps** [comment]
![image](https://user-images.githubusercontent.com/71562383/144971200-6736fea2-2a9d-4d9c-a58d-d7bdebcbdc3d.png)

**Comment by marksie1988** [comment]
Hi, I'm not sure what is causing that to happen. Possibly some of the div's that are required for the card to work correctly. 

If you are able to pinpoint what is causing that I can look at fixing it. However I don't have the same theme you are using so not sure I would find it unless I can get that theme somewhere

**Comment by marksie1988** [comment]
@Andrewpaps  please could you test with the latest version, this may now be resolved by #552

**Comment by marksie1988** [comment]
Closing this out as there has been no update, let me know if that didn't resolve the issue

**Comment by Andrewpaps** [comment]
Neither the Home Assistant update nor any Integration update have resolved the issue unfortunately.

![image](https://user-images.githubusercontent.com/71562383/149319276-141e91bc-d4f7-46ab-af00-84a59ac95a0f.png)

**Comment by KredeDK** [comment]
You can fix it by setting the top and bottom padding to 0px of ha-card. 
```
card_mod:
  style: |
    ha-card {
      padding-top: 0px !important;
      padding-bottom: 0px !important;
    }
```

**Comment by Andrewpaps** [comment]
> You can fix it by setting the top and bottom padding to 0px of ha-card.
> 
> ```
> card_mod:
>   style: |
>     ha-card {
>       padding-top: 0px !important;
>       padding-bottom: 0px !important;
>     }
> ```

Already tried it, doesn't fix the issue as card_mod only applies to padding within the card.

As you can see, for some reason the extra padding is happening exterior to the card but is still definitely being caused by the atomic calendar card itself.

**Comment by abeltman** [comment]
@Andrewpaps ... I am experiencing the same issue. Did you ever get it resolved?

**Comment by abeltman** [comment]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/79146243/189695752-f4a63035-d0a4-4e72-be6e-23753b5f8db6.png">
